import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { writeCapabilityStatement } from "@/lib/capability-writer";
import PDFDocument from "pdfkit";
import { rateLimit } from "@/lib/rate-limit";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

// ---------- constants ----------
const BLUE = "#2563eb";
const DARK = "#1e293b";
const GRAY = "#64748b";
const LIGHT_BG = "#f1f5f9";
const PAGE_W = 612; // letter
const PAGE_H = 792;
const MARGIN = 54; // 0.75 in
const CONTENT_W = PAGE_W - MARGIN * 2;

// ---------- helpers ----------

/** Parse the markdown generated by capability-writer into sections. */
function parseSections(md: string): { title: string; body: string }[] {
  const sections: { title: string; body: string }[] = [];
  const lines = md.split("\n");
  let current: { title: string; body: string } | null = null;

  for (const line of lines) {
    const h2 = line.match(/^##\s+(.+)/);
    if (h2) {
      if (current) sections.push(current);
      current = { title: h2[1].trim(), body: "" };
    } else if (current) {
      current.body += line + "\n";
    }
  }
  if (current) sections.push(current);
  return sections;
}

/** Render a section header with blue accent bar. */
function drawSectionHeader(doc: PDFKit.PDFDocument, title: string, y: number): number {
  // check page break
  if (y + 30 > PAGE_H - MARGIN) {
    doc.addPage();
    y = MARGIN;
  }
  doc.save();
  doc.rect(MARGIN, y, 3, 16).fill(BLUE);
  doc
    .font("Helvetica-Bold")
    .fontSize(13)
    .fillColor(DARK)
    .text(title.toUpperCase(), MARGIN + 10, y + 1, { width: CONTENT_W - 10 });
  doc.restore();
  // thin rule below
  const lineY = y + 20;
  doc
    .moveTo(MARGIN, lineY)
    .lineTo(PAGE_W - MARGIN, lineY)
    .strokeColor("#cbd5e1")
    .lineWidth(0.5)
    .stroke();
  return lineY + 8;
}

/** Render body text (bullets and paragraphs). Returns new Y. */
function drawBody(doc: PDFKit.PDFDocument, body: string, startY: number): number {
  let y = startY;
  const lines = body.split("\n");

  for (const raw of lines) {
    const line = raw.trim();
    if (!line) {
      y += 4;
      continue;
    }

    // check page break
    if (y + 14 > PAGE_H - MARGIN) {
      doc.addPage();
      y = MARGIN;
    }

    const bullet = line.match(/^[-*]\s+(.*)/);
    if (bullet) {
      // bullet character
      doc.font("Helvetica").fontSize(10).fillColor(BLUE);
      doc.text("\u2022", MARGIN + 6, y, { continued: false });
      doc.font("Helvetica").fontSize(10).fillColor(DARK);
      const textHeight = doc.heightOfString(bullet[1], {
        width: CONTENT_W - 22,
      });
      doc.text(bullet[1], MARGIN + 18, y, { width: CONTENT_W - 22 });
      y += textHeight + 4;
    } else {
      // Bold lines (### or **text**)
      const boldMatch = line.match(/^(?:###?\s+)?(?:\*\*(.+?)\*\*|(.+))$/);
      const isBold = line.startsWith("###") || line.startsWith("**");
      const content = boldMatch
        ? boldMatch[1] || boldMatch[2] || line
        : line;

      doc
        .font(isBold ? "Helvetica-Bold" : "Helvetica")
        .fontSize(10)
        .fillColor(DARK);
      const textHeight = doc.heightOfString(content, { width: CONTENT_W });
      doc.text(content, MARGIN, y, { width: CONTENT_W });
      y += textHeight + 4;
    }
  }
  return y + 2;
}

/** Draw the Corporate Data section as a formatted table. */
function drawCorporateTable(
  doc: PDFKit.PDFDocument,
  org: {
    uei?: string | null;
    cage_code?: string | null;
    naics_codes?: string[] | null;
    certifications?: string[] | null;
  },
  startY: number
): number {
  let y = startY;

  const rows: [string, string][] = [];
  if (org.uei) rows.push(["UEI", org.uei]);
  if (org.cage_code) rows.push(["CAGE Code", org.cage_code]);
  if (org.naics_codes?.length)
    rows.push(["NAICS Codes", org.naics_codes.join(", ")]);
  if (org.certifications?.length)
    rows.push(["Certifications", org.certifications.join(", ")]);

  if (!rows.length) return y;

  const ROW_H = 22;
  const LABEL_W = 120;
  const VALUE_W = CONTENT_W - LABEL_W;

  // check page break for the whole table
  if (y + rows.length * ROW_H + 10 > PAGE_H - MARGIN) {
    doc.addPage();
    y = MARGIN;
  }

  for (let i = 0; i < rows.length; i++) {
    const rowY = y + i * ROW_H;
    // alternating background
    if (i % 2 === 0) {
      doc.save();
      doc.rect(MARGIN, rowY, CONTENT_W, ROW_H).fill(LIGHT_BG);
      doc.restore();
    }
    doc
      .font("Helvetica-Bold")
      .fontSize(9)
      .fillColor(GRAY)
      .text(rows[i][0], MARGIN + 8, rowY + 6, { width: LABEL_W - 8 });
    doc
      .font("Helvetica")
      .fontSize(9)
      .fillColor(DARK)
      .text(rows[i][1], MARGIN + LABEL_W, rowY + 6, { width: VALUE_W - 8 });
  }
  return y + rows.length * ROW_H + 6;
}

/** Build the full PDF document as a Buffer. */
async function buildPdf(
  org: {
    name: string;
    uei?: string | null;
    cage_code?: string | null;
    naics_codes?: string[] | null;
    certifications?: string[] | null;
    entity_description?: string | null;
  },
  markdown: string
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "LETTER",
      margins: { top: MARGIN, bottom: MARGIN, left: MARGIN, right: MARGIN },
      bufferPages: true,
      info: {
        Title: `${org.name} - Capability Statement`,
        Author: "ContractsIntel",
      },
    });

    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // ===== HEADER =====
    let y = MARGIN;

    // Logo placeholder: blue rounded box with "CI"
    doc.save();
    doc.roundedRect(MARGIN, y, 44, 44, 6).fill(BLUE);
    doc.font("Helvetica-Bold").fontSize(18).fillColor("#ffffff");
    doc.text("CI", MARGIN + 10, y + 12, { width: 24 });
    doc.restore();

    // Company name
    doc
      .font("Helvetica-Bold")
      .fontSize(20)
      .fillColor(DARK)
      .text(org.name, MARGIN + 54, y + 4, { width: CONTENT_W - 54 });

    // Tagline
    doc
      .font("Helvetica")
      .fontSize(10)
      .fillColor(GRAY)
      .text("Capability Statement", MARGIN + 54, y + 28, {
        width: CONTENT_W - 54,
      });

    y += 54;

    // header rule
    doc
      .moveTo(MARGIN, y)
      .lineTo(PAGE_W - MARGIN, y)
      .strokeColor(BLUE)
      .lineWidth(2)
      .stroke();
    y += 12;

    // ===== SECTIONS =====
    const sections = parseSections(markdown);

    for (const section of sections) {
      const titleLower = section.title.toLowerCase();
      // Corporate Data gets the table treatment
      if (titleLower.includes("corporate data")) {
        y = drawSectionHeader(doc, section.title, y);
        y = drawCorporateTable(doc, org, y);
        // Also render any extra body text in this section (like POC info)
        const extraBody = section.body
          .split("\n")
          .filter((l) => {
            const t = l.trim();
            // skip lines that are just the table data we already rendered
            return (
              t &&
              !t.match(
                /^[-*]\s*\*?\*?(UEI|CAGE|NAICS|Certification)/i
              )
            );
          })
          .join("\n");
        if (extraBody.trim()) {
          y = drawBody(doc, extraBody, y);
        }
      } else {
        y = drawSectionHeader(doc, section.title, y);
        y = drawBody(doc, section.body, y);
      }
    }

    // ===== FOOTER on every page =====
    const pageCount = doc.bufferedPageRange().count;
    for (let i = 0; i < pageCount; i++) {
      doc.switchToPage(i);
      doc
        .font("Helvetica")
        .fontSize(7)
        .fillColor(GRAY)
        .text(
          `Generated by ContractsIntel  |  ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}  |  Page ${i + 1} of ${pageCount}`,
          MARGIN,
          PAGE_H - 36,
          { width: CONTENT_W, align: "center" }
        );
      // bottom accent line
      doc
        .moveTo(MARGIN, PAGE_H - 42)
        .lineTo(PAGE_W - MARGIN, PAGE_H - 42)
        .strokeColor(BLUE)
        .lineWidth(0.5)
        .stroke();
    }

    doc.end();
  });
}

// ---------- route handlers ----------

async function handlePdfRequest(supabase: any, organizationId: string) {
  // Fetch org
  const { data: org } = await supabase
    .from("organizations")
    .select(
      "id, name, uei, cage_code, naics_codes, certifications, entity_description, keywords"
    )
    .eq("id", organizationId)
    .single();

  if (!org) {
    return NextResponse.json(
      { error: "Organization not found" },
      { status: 404 }
    );
  }

  // Try to fetch the latest existing capability statement
  let markdown: string | null = null;

  const { data: existing } = await supabase
    .from("capability_statements")
    .select("markdown")
    .eq("organization_id", organizationId)
    .order("created_at", { ascending: false })
    .limit(1)
    .single();

  if (existing?.markdown) {
    markdown = existing.markdown;
  } else {
    // Generate a new one on the fly
    const { data: pastPerf } = await supabase
      .from("past_performance")
      .select(
        "contract_title, contract_name, agency, contract_number, contract_value, award_amount, period_of_performance, description"
      )
      .eq("organization_id", organizationId)
      .order("created_at", { ascending: false })
      .limit(20);

    const result = await writeCapabilityStatement({
      organization: org,
      past_performance: pastPerf ?? [],
    });
    markdown = result.markdown;
  }

  if (!markdown) {
    return NextResponse.json(
      { error: "Failed to produce capability statement" },
      { status: 500 }
    );
  }

  const pdfBuffer = await buildPdf(org, markdown);

  const safeName = org.name.replace(/[^a-zA-Z0-9_-]/g, "_").slice(0, 60);

  return new NextResponse(new Uint8Array(pdfBuffer), {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${safeName}_Capability_Statement.pdf"`,
      "Content-Length": String(pdfBuffer.length),
    },
  });
}

export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();
    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const rl = rateLimit(`ai:${user.id}`, 10, 60_000);
    if (!rl.allowed) {
      return NextResponse.json(
        { error: "Rate limit exceeded. Try again shortly." },
        { status: 429 },
      );
    }

    // Accept organization_id from body, or fall back to user's org
    let organizationId: string | null = null;

    try {
      const body = await request.json();
      organizationId = body.organization_id ?? null;
    } catch {
      // no body or invalid JSON — that's fine
    }

    if (!organizationId) {
      const { data: userRecord } = await supabase
        .from("users")
        .select("organization_id")
        .eq("auth_id", user.id)
        .single();
      organizationId = userRecord?.organization_id ?? null;
    }

    if (!organizationId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    return handlePdfRequest(supabase, organizationId);
  } catch (err: any) {
    console.error("capability-statement/pdf POST error:", err);
    return NextResponse.json(
      { error: err?.message ?? "Internal error" },
      { status: 500 }
    );
  }
}

export async function GET(_request: NextRequest) {
  try {
    const supabase = await createClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();
    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { data: userRecord } = await supabase
      .from("users")
      .select("organization_id")
      .eq("auth_id", user.id)
      .single();

    if (!userRecord?.organization_id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    return handlePdfRequest(supabase, userRecord.organization_id);
  } catch (err: any) {
    console.error("capability-statement/pdf GET error:", err);
    return NextResponse.json(
      { error: err?.message ?? "Internal error" },
      { status: 500 }
    );
  }
}
