// Top ~200 NAICS codes with plain English descriptions for search
// Covers the most common government contracting categories
export const NAICS_LOOKUP: { code: string; title: string; keywords: string }[] = [
  // Professional Services
  { code: "541511", title: "Custom Computer Programming Services", keywords: "software development coding programming web apps" },
  { code: "541512", title: "Computer Systems Design Services", keywords: "IT consulting systems integration technology design" },
  { code: "541513", title: "Computer Facilities Management Services", keywords: "data center managed IT hosting operations" },
  { code: "541519", title: "Other Computer Related Services", keywords: "IT support help desk tech services cloud" },
  { code: "541611", title: "Administrative Management Consulting", keywords: "management consulting business strategy advisory" },
  { code: "541612", title: "Human Resources Consulting", keywords: "HR staffing workforce talent management recruiting" },
  { code: "541613", title: "Marketing Consulting Services", keywords: "marketing branding advertising strategy consulting" },
  { code: "541614", title: "Process & Logistics Consulting", keywords: "supply chain logistics operations process improvement" },
  { code: "541618", title: "Other Management Consulting", keywords: "consulting advisory professional services" },
  { code: "541620", title: "Environmental Consulting", keywords: "environmental remediation assessment compliance green" },
  { code: "541690", title: "Other Scientific & Technical Consulting", keywords: "scientific technical research consulting analysis" },
  { code: "541330", title: "Engineering Services", keywords: "engineering design civil mechanical electrical structural" },
  { code: "541310", title: "Architectural Services", keywords: "architecture building design planning" },
  { code: "541320", title: "Landscape Architectural Services", keywords: "landscape design outdoor planning parks" },
  { code: "541340", title: "Drafting Services", keywords: "drafting CAD technical drawing blueprints" },
  { code: "541350", title: "Building Inspection Services", keywords: "building inspection compliance safety code" },
  { code: "541360", title: "Geophysical Surveying & Mapping", keywords: "surveying mapping geospatial GIS" },
  { code: "541370", title: "Surveying & Mapping Services", keywords: "land survey boundary mapping cartography" },
  { code: "541380", title: "Testing Laboratories", keywords: "lab testing quality assurance QA analysis" },
  { code: "541410", title: "Interior Design Services", keywords: "interior design space planning furnishing" },
  { code: "541420", title: "Industrial Design Services", keywords: "product design industrial manufacturing design" },
  { code: "541430", title: "Graphic Design Services", keywords: "graphic design visual branding creative" },
  { code: "541490", title: "Other Specialized Design Services", keywords: "design UX UI specialized creative" },
  { code: "541710", title: "R&D in Physical & Life Sciences", keywords: "research development science lab biotech pharmaceutical" },
  { code: "541715", title: "R&D in Nanotechnology", keywords: "nanotechnology research advanced materials" },
  { code: "541720", title: "R&D in Social Sciences & Humanities", keywords: "research social science policy analysis" },
  { code: "541810", title: "Advertising Agencies", keywords: "advertising agency creative campaigns" },
  { code: "541820", title: "Public Relations Agencies", keywords: "public relations PR communications media" },
  { code: "541830", title: "Media Buying Agencies", keywords: "media buying planning placement advertising" },
  { code: "541840", title: "Media Representatives", keywords: "media sales representation advertising" },
  { code: "541860", title: "Direct Mail Advertising", keywords: "direct mail marketing postal campaigns" },
  { code: "541870", title: "Advertising Material Distribution", keywords: "marketing materials distribution signage" },
  { code: "541910", title: "Marketing Research & Public Opinion", keywords: "market research surveys polls focus groups" },
  { code: "541921", title: "Photography Studios", keywords: "photography photo studio imaging" },
  { code: "541922", title: "Commercial Photography", keywords: "commercial photography professional imaging" },
  { code: "541930", title: "Translation & Interpretation", keywords: "translation interpretation language services linguist" },
  { code: "541990", title: "All Other Professional Services", keywords: "professional services consulting specialized" },

  // Construction
  { code: "236115", title: "New Single-Family Housing Construction", keywords: "residential construction homebuilding houses" },
  { code: "236116", title: "New Multifamily Housing Construction", keywords: "apartments condos multifamily construction" },
  { code: "236117", title: "New Housing Operative Builders", keywords: "housing development real estate construction" },
  { code: "236118", title: "Residential Remodelers", keywords: "renovation remodeling home improvement repair" },
  { code: "236210", title: "Industrial Building Construction", keywords: "industrial factory warehouse construction" },
  { code: "236220", title: "Commercial Building Construction", keywords: "commercial office retail construction general contractor" },
  { code: "237110", title: "Water & Sewer Line Construction", keywords: "water sewer pipeline utility infrastructure" },
  { code: "237120", title: "Oil & Gas Pipeline Construction", keywords: "oil gas pipeline energy infrastructure" },
  { code: "237130", title: "Power & Communication Line Construction", keywords: "electrical power telecom lines infrastructure" },
  { code: "237210", title: "Land Subdivision", keywords: "land development subdivision grading" },
  { code: "237310", title: "Highway & Street Construction", keywords: "road highway bridge street paving DOT" },
  { code: "237990", title: "Other Heavy & Civil Engineering", keywords: "civil engineering heavy construction infrastructure" },
  { code: "238110", title: "Poured Concrete Foundation", keywords: "concrete foundation masonry structural" },
  { code: "238120", title: "Structural Steel & Precast Concrete", keywords: "steel erection precast structural" },
  { code: "238130", title: "Framing Contractors", keywords: "framing carpentry wood construction" },
  { code: "238140", title: "Masonry Contractors", keywords: "masonry brick stone block" },
  { code: "238150", title: "Glass & Glazing Contractors", keywords: "glass glazing windows curtain wall" },
  { code: "238160", title: "Roofing Contractors", keywords: "roofing repair replacement commercial" },
  { code: "238210", title: "Electrical Contractors", keywords: "electrical wiring lighting power installation" },
  { code: "238220", title: "Plumbing & HVAC Contractors", keywords: "plumbing HVAC heating cooling air conditioning" },
  { code: "238290", title: "Other Building Equipment Contractors", keywords: "elevator fire suppression specialty equipment" },
  { code: "238310", title: "Drywall & Insulation Contractors", keywords: "drywall insulation interior walls" },
  { code: "238320", title: "Painting & Wall Covering", keywords: "painting wallpaper coating finishing" },
  { code: "238330", title: "Flooring Contractors", keywords: "flooring carpet tile hardwood installation" },
  { code: "238340", title: "Tile & Terrazzo Contractors", keywords: "tile terrazzo ceramic stone flooring" },
  { code: "238350", title: "Finish Carpentry Contractors", keywords: "finish carpentry millwork trim cabinets" },
  { code: "238390", title: "Other Building Finishing", keywords: "building finishing specialty trade" },
  { code: "238910", title: "Site Preparation Contractors", keywords: "excavation grading demolition site prep" },
  { code: "238990", title: "All Other Specialty Trade", keywords: "specialty contractor trade construction" },

  // Information Technology & Telecom
  { code: "511210", title: "Software Publishers", keywords: "software SaaS product publishing applications" },
  { code: "517111", title: "Wired Telecommunications Carriers", keywords: "telecom internet ISP broadband fiber" },
  { code: "517112", title: "Wireless Telecommunications Carriers", keywords: "wireless mobile cellular 5G telecom" },
  { code: "517911", title: "Telecommunications Resellers", keywords: "telecom reseller phone service" },
  { code: "517919", title: "All Other Telecommunications", keywords: "satellite telecom communications" },
  { code: "518210", title: "Data Processing & Hosting", keywords: "cloud hosting data center processing AWS Azure" },
  { code: "519130", title: "Internet Publishing & Web Search", keywords: "web publishing portals search engines content" },
  { code: "519190", title: "All Other Information Services", keywords: "information services data analytics" },

  // Healthcare
  { code: "621111", title: "Offices of Physicians", keywords: "medical doctor physician healthcare clinic" },
  { code: "621210", title: "Offices of Dentists", keywords: "dental dentist oral healthcare" },
  { code: "621310", title: "Offices of Chiropractors", keywords: "chiropractic wellness" },
  { code: "621320", title: "Offices of Optometrists", keywords: "optometry eye care vision" },
  { code: "621330", title: "Offices of Mental Health", keywords: "mental health counseling therapy psychology" },
  { code: "621340", title: "Offices of Physical Therapists", keywords: "physical therapy rehabilitation PT" },
  { code: "621399", title: "Offices of All Other Health Practitioners", keywords: "healthcare practitioner alternative medicine" },
  { code: "621410", title: "Family Planning Centers", keywords: "family planning reproductive health" },
  { code: "621420", title: "Outpatient Mental Health Centers", keywords: "mental health outpatient behavioral" },
  { code: "621491", title: "HMO Medical Centers", keywords: "HMO managed care health center" },
  { code: "621492", title: "Kidney Dialysis Centers", keywords: "dialysis renal kidney" },
  { code: "621498", title: "All Other Outpatient Care Centers", keywords: "outpatient care ambulatory clinic" },
  { code: "621511", title: "Medical Laboratories", keywords: "medical lab testing diagnostics blood" },
  { code: "621512", title: "Diagnostic Imaging Centers", keywords: "radiology imaging MRI CT scan X-ray" },
  { code: "621610", title: "Home Health Care Services", keywords: "home health nursing aide caregiving" },
  { code: "621910", title: "Ambulance Services", keywords: "ambulance EMS emergency medical transport" },
  { code: "621999", title: "All Other Ambulatory Health Care", keywords: "healthcare ambulatory miscellaneous" },
  { code: "622110", title: "General Medical & Surgical Hospitals", keywords: "hospital medical surgical inpatient" },
  { code: "623110", title: "Nursing Care Facilities", keywords: "nursing home long-term care skilled nursing" },

  // Facilities & Maintenance
  { code: "561210", title: "Facilities Support Services", keywords: "facilities management building operations maintenance" },
  { code: "561310", title: "Employment Placement Agencies", keywords: "staffing recruiting temp agency placement" },
  { code: "561320", title: "Temporary Help Services", keywords: "temp staffing temporary workers contract staff" },
  { code: "561330", title: "Professional Employer Organizations", keywords: "PEO employer services HR outsourcing" },
  { code: "561410", title: "Document Preparation Services", keywords: "document scanning printing copying preparation" },
  { code: "561421", title: "Telephone Answering Services", keywords: "call center answering service phone support" },
  { code: "561422", title: "Telemarketing & Call Centers", keywords: "telemarketing call center outbound inbound" },
  { code: "561431", title: "Private Mail Centers", keywords: "mail center shipping receiving postal" },
  { code: "561440", title: "Collection Agencies", keywords: "debt collection recovery" },
  { code: "561450", title: "Credit Bureaus", keywords: "credit reporting bureau scoring" },
  { code: "561499", title: "All Other Business Support Services", keywords: "business support services admin" },
  { code: "561510", title: "Travel Agencies", keywords: "travel agency booking tourism" },
  { code: "561520", title: "Tour Operators", keywords: "tour operator travel group excursion" },
  { code: "561599", title: "All Other Travel Services", keywords: "travel services logistics" },
  { code: "561611", title: "Investigation Services", keywords: "investigation detective private security" },
  { code: "561612", title: "Security Guards & Patrol Services", keywords: "security guard patrol protection officer" },
  { code: "561613", title: "Armored Car Services", keywords: "armored car cash transport security" },
  { code: "561621", title: "Security Systems Services", keywords: "alarm security systems installation monitoring" },
  { code: "561710", title: "Exterminating & Pest Control", keywords: "pest control exterminator bug treatment" },
  { code: "561720", title: "Janitorial Services", keywords: "janitorial cleaning custodial commercial cleaning" },
  { code: "561730", title: "Landscaping Services", keywords: "landscaping lawn care grounds maintenance mowing" },
  { code: "561740", title: "Carpet & Upholstery Cleaning", keywords: "carpet cleaning upholstery floor care" },
  { code: "561790", title: "Other Services to Buildings", keywords: "building services maintenance window cleaning" },
  { code: "561910", title: "Packaging & Labeling Services", keywords: "packaging labeling fulfillment shipping" },
  { code: "561920", title: "Convention & Trade Show Organizers", keywords: "event planning convention trade show conference" },
  { code: "561990", title: "All Other Support Services", keywords: "support services miscellaneous business" },

  // Manufacturing
  { code: "332710", title: "Machine Shops", keywords: "machining CNC metal fabrication precision parts" },
  { code: "332721", title: "Precision Turned Product Manufacturing", keywords: "turned parts screw machine precision" },
  { code: "332999", title: "All Other Miscellaneous Fabricated Metal", keywords: "metal fabrication manufacturing metalwork" },
  { code: "333111", title: "Farm Machinery Manufacturing", keywords: "farm equipment agriculture machinery" },
  { code: "333314", title: "Optical Instrument Manufacturing", keywords: "optical instruments lenses cameras" },
  { code: "333316", title: "Photographic & Photocopying Equipment", keywords: "photocopier printer imaging equipment" },
  { code: "333611", title: "Turbine Manufacturing", keywords: "turbine engine power generation" },
  { code: "334111", title: "Electronic Computer Manufacturing", keywords: "computer hardware PC server manufacturing" },
  { code: "334112", title: "Computer Storage Device Manufacturing", keywords: "hard drive SSD storage device" },
  { code: "334118", title: "Computer Terminal & Peripheral Manufacturing", keywords: "peripheral keyboard mouse monitor" },
  { code: "334210", title: "Telephone Apparatus Manufacturing", keywords: "phone telephone communications equipment" },
  { code: "334220", title: "Radio & TV Broadcasting Equipment", keywords: "broadcast radio TV transmission equipment" },
  { code: "334290", title: "Other Communications Equipment", keywords: "communications networking equipment telecom" },
  { code: "334310", title: "Audio & Video Equipment Manufacturing", keywords: "audio video AV equipment multimedia" },
  { code: "334412", title: "Bare Printed Circuit Board Manufacturing", keywords: "PCB circuit board electronics" },
  { code: "334413", title: "Semiconductor Manufacturing", keywords: "semiconductor chip microchip integrated circuit" },
  { code: "334511", title: "Search & Navigation Equipment", keywords: "radar GPS navigation detection instruments" },
  { code: "334516", title: "Analytical Laboratory Instruments", keywords: "lab instruments analytical testing equipment" },
  { code: "336411", title: "Aircraft Manufacturing", keywords: "aircraft airplane aerospace aviation" },
  { code: "336413", title: "Other Aircraft Parts Manufacturing", keywords: "aircraft parts aerospace components" },
  { code: "336414", title: "Guided Missile & Space Vehicle Manufacturing", keywords: "missile rocket space defense weapons" },
  { code: "336992", title: "Military Armored Vehicle Manufacturing", keywords: "military vehicles armored tanks defense" },

  // Transportation & Logistics
  { code: "484110", title: "General Freight Trucking, Local", keywords: "trucking local freight delivery transport" },
  { code: "484121", title: "General Freight Trucking, Long-Distance", keywords: "trucking long-distance freight shipping OTR" },
  { code: "484210", title: "Used Household Goods Moving", keywords: "moving relocation household furniture" },
  { code: "484220", title: "Specialized Freight Trucking", keywords: "specialized freight heavy haul oversized" },
  { code: "488190", title: "Other Support Activities for Air Transport", keywords: "airport ground handling aviation support" },
  { code: "488510", title: "Freight Transportation Arrangement", keywords: "freight broker logistics 3PL arranging" },
  { code: "492110", title: "Couriers & Express Delivery", keywords: "courier delivery express overnight package" },
  { code: "493110", title: "General Warehousing & Storage", keywords: "warehouse storage distribution fulfillment" },

  // Education & Training
  { code: "611310", title: "Colleges & Universities", keywords: "college university higher education" },
  { code: "611410", title: "Business & Secretarial Schools", keywords: "business school training vocational" },
  { code: "611420", title: "Computer Training", keywords: "computer training IT education certification" },
  { code: "611430", title: "Professional & Management Training", keywords: "professional development management training leadership" },
  { code: "611512", title: "Flight Training", keywords: "flight training pilot aviation school" },
  { code: "611519", title: "Other Technical & Trade Schools", keywords: "trade school technical training vocational" },
  { code: "611610", title: "Fine Arts Schools", keywords: "art school creative fine arts education" },
  { code: "611691", title: "Exam Preparation & Tutoring", keywords: "tutoring test prep SAT GRE education" },
  { code: "611699", title: "All Other Miscellaneous Schools", keywords: "training school education miscellaneous" },
  { code: "611710", title: "Educational Support Services", keywords: "educational consulting curriculum assessment" },

  // Waste & Remediation
  { code: "562111", title: "Solid Waste Collection", keywords: "trash garbage waste collection hauling" },
  { code: "562112", title: "Hazardous Waste Collection", keywords: "hazardous waste hazmat collection disposal" },
  { code: "562119", title: "Other Waste Collection", keywords: "waste collection recycling" },
  { code: "562211", title: "Hazardous Waste Treatment & Disposal", keywords: "hazardous waste treatment disposal remediation" },
  { code: "562910", title: "Remediation Services", keywords: "environmental remediation cleanup contamination" },
  { code: "562998", title: "All Other Miscellaneous Waste Management", keywords: "waste management environmental services" },

  // Retail & Wholesale
  { code: "423420", title: "Office Equipment Wholesale", keywords: "office equipment supplies wholesale distribution" },
  { code: "423430", title: "Computer Equipment Wholesale", keywords: "computer hardware wholesale distribution IT" },
  { code: "423440", title: "Other Electronic Parts Wholesale", keywords: "electronics parts components wholesale" },
  { code: "423450", title: "Medical Equipment Wholesale", keywords: "medical equipment devices supplies wholesale" },
  { code: "423490", title: "Other Professional Equipment Wholesale", keywords: "professional equipment wholesale laboratory" },
  { code: "423610", title: "Electrical Supplies Wholesale", keywords: "electrical supplies wire cable wholesale" },
  { code: "423690", title: "Other Electronic Parts & Equipment", keywords: "electronic equipment wholesale distribution" },
  { code: "423710", title: "Hardware Wholesale", keywords: "hardware tools fasteners wholesale" },
  { code: "423720", title: "Plumbing Supplies Wholesale", keywords: "plumbing pipe fittings valves wholesale" },
  { code: "423810", title: "Construction Materials Wholesale", keywords: "construction materials lumber building wholesale" },
  { code: "423820", title: "Farm & Garden Supplies Wholesale", keywords: "farm garden agricultural supplies wholesale" },
  { code: "423840", title: "Industrial Supplies Wholesale", keywords: "industrial supplies MRO wholesale" },
  { code: "423860", title: "Transportation Equipment Wholesale", keywords: "vehicle transportation equipment wholesale" },
  { code: "424120", title: "Stationery & Office Supplies Wholesale", keywords: "office supplies paper stationery wholesale" },

  // Finance & Insurance
  { code: "522110", title: "Commercial Banking", keywords: "bank banking commercial lending finance" },
  { code: "522310", title: "Mortgage & Nonmortgage Loan Brokers", keywords: "mortgage loan broker lending finance" },
  { code: "523110", title: "Investment Banking & Securities", keywords: "investment banking securities trading finance" },
  { code: "524113", title: "Direct Life Insurance Carriers", keywords: "life insurance carrier underwriting" },
  { code: "524114", title: "Direct Health & Medical Insurance", keywords: "health insurance medical coverage" },
  { code: "524126", title: "Direct Property & Casualty Insurance", keywords: "property casualty insurance P&C" },
  { code: "524210", title: "Insurance Agencies & Brokerages", keywords: "insurance agent broker agency" },
  { code: "524291", title: "Claims Adjusting", keywords: "claims adjusting insurance investigation" },
  { code: "524292", title: "Third Party Administration of Insurance", keywords: "TPA claims administration insurance" },
  { code: "541211", title: "Offices of Certified Public Accountants", keywords: "CPA accounting audit tax preparation" },
  { code: "541213", title: "Tax Preparation Services", keywords: "tax preparation filing returns" },
  { code: "541214", title: "Payroll Services", keywords: "payroll processing employee compensation" },
  { code: "541219", title: "Other Accounting Services", keywords: "bookkeeping accounting financial services" },
];

export function searchNaics(query: string): typeof NAICS_LOOKUP {
  if (!query || query.length < 2) return [];
  const q = query.toLowerCase();
  return NAICS_LOOKUP.filter(
    (n) =>
      n.code.startsWith(q) ||
      n.title.toLowerCase().includes(q) ||
      n.keywords.includes(q)
  ).slice(0, 10);
}
